# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_Fcode(object):
    def setupUi(self, Fcode):
        Fcode.setObjectName("Fcode")
        Fcode.resize(1075, 602)
        self.background = QtWidgets.QLabel(Fcode)
        self.background.setGeometry(QtCore.QRect(0, 0, 1081, 601))
        self.background.setMouseTracking(False)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("background-image: url(:/background/background.jpg);")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/background/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setWordWrap(False)
        self.background.setOpenExternalLinks(False)
        self.background.setObjectName("background")
        self.CancelBTN = QtWidgets.QPushButton(Fcode)
        self.CancelBTN.setGeometry(QtCore.QRect(870, 510, 182, 51))
        self.CancelBTN.setSizeIncrement(QtCore.QSize(50, 50))
        self.CancelBTN.setStyleSheet("QPushButton#btnGoToHome {\n"
                                    "    background-color: \"#FFFFFF\";\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 10px;\n"
                                    "    font: bold 16px;\n"
                                    "    min-width: 10em;\n"
                                    "    padding: 6px;\n"
                                    "    color: rgb(45, 7, 0);\n"
                                    "}")
        self.CancelBTN.setAutoRepeat(False)
        self.CancelBTN.setAutoDefault(False)
        self.CancelBTN.setDefault(False)
        self.CancelBTN.setObjectName("CancelBTN")
        self.gridLayoutWidget = QtWidgets.QWidget(Fcode)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.FeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FeedLabel.setObjectName("FeedLabel")
        self.gridLayout.addWidget(self.FeedLabel, 0, 0, 0, 0)
        self.QrCodeData = QtWidgets.QLabel(Fcode)
        self.QrCodeData.setStyleSheet("QLabel {color: '#FFFFFF'; font-size: 18px}")
        self.QrCodeData.setWordWrap(True)
        self.QrCodeData.setGeometry(QtCore.QRect(550, 85, 250, 30))
        self.QrCodeData.setObjectName("QrCodeData")
        self.labelData = QtWidgets.QLabel(Fcode)
        self.labelData.setGeometry(QtCore.QRect(10, 510, 47, 16))
        self.labelData.setObjectName("labelData")

        self.retranslateUi(Fcode)
        QtCore.QMetaObject.connectSlotsByName(Fcode)

    def retranslateUi(self, Fcode):
        _translate = QtCore.QCoreApplication.translate
        Fcode.setWindowTitle(_translate("Fcode", "Frame"))
        self.CancelBTN.setText(_translate("Fcode", "Quit"))
        self.FeedLabel.setStyleSheet("QLabel {border:5px solid white; border-radius: 20px; background-color: transparent;}")
        self.FeedLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.FeedLabel.setMaximumSize(QtCore.QSize(300, 300))
        self.movie = QMovie("./res/qr-code-scanner.gif")
        self.FeedLabel.setMovie(self.movie)
        self.movie.start()
        self.QrCodeData.setText(_translate("Fcode", "Scanning..."))
        self.labelData.setText(_translate("Fcode", "Data:"))
import background_rc
import qrcode_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fcode = QtWidgets.QFrame()
    ui = Ui_Fcode()
    ui.setupUi(Fcode)
    Fcode.show()
    sys.exit(app.exec_())
