# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QMovie

class Ui_Fcode(object):
    def setupUi(self, Fcode):
        Fcode.setObjectName("Fcode")
        Fcode.resize(1075, 602)
        self.background = QtWidgets.QLabel(Fcode)
        self.background.setGeometry(QtCore.QRect(0, 0, 1081, 601))
        self.background.setMouseTracking(False)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("background-image: url(:/background/background.jpg);")
        self.background.setPixmap(QtGui.QPixmap(":/background/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setWordWrap(False)
        self.background.setOpenExternalLinks(False)
        self.background.setObjectName("background")

        self.CancelBTN = QtWidgets.QPushButton(Fcode)
        self.CancelBTN.setGeometry(QtCore.QRect(870, 500, 150, 51))
        self.CancelBTN.setSizeIncrement(QtCore.QSize(30, 50))
        self.CancelBTN.setStyleSheet("QPushButton#CancelBTN {\n"
                                    "    background-color: \"#FFFFFF\";\n"
                                    "    border-style: outset;\n"
                                    "    border-radius: 5px;\n"
                                    "    font: bold 16px;\n"
                                    "    min-width: 5em;\n"
                                    "    padding: 2px;\n"
                                    "    color: rgb(45, 7, 0);\n"
                                    "}")
        self.CancelBTN.setAutoRepeat(False)
        self.CancelBTN.setAutoDefault(False)
        self.CancelBTN.setDefault(False)
        self.CancelBTN.setObjectName("CancelBTN")

        self.current = QtWidgets.QLabel(Fcode)
        self.current.setGeometry(QtCore.QRect(600, 20, 300, 100))
        self.current.setStyleSheet("QLabel {color: '#FFFFFF'; font-size: 20px; font-wight: bold; font-weight: bold;}")

        self.history = QtWidgets.QLabel(Fcode)
        self.history.setGeometry(QtCore.QRect(600, 220, 300, 100))
        self.history.setStyleSheet("QLabel {color: '#FFFFFF'; font-size: 20px; font-wight: bold;font-weight: bold;}")

        self.listWidget = QtWidgets.QListWidget(Fcode)
        self.listWidget.setGeometry(QtCore.QRect(600, 300, 300, 150))
        self.listWidget.setStyleSheet("QListWidget { background: transparent; border-radius: 10px; padding: 5px; border: 4px solid white;} "
                                      "QListWidget::item { background: white; border-radius: 4px; padding: 2px; margin: 2px } "
                                      "QListWidget::item:selected { background: blue; }")
        self.listWidget.show()

        self.gridLayoutWidget = QtWidgets.QWidget(Fcode)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.FeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FeedLabel.setObjectName("FeedLabel")
        self.gridLayout.addWidget(self.FeedLabel, 0, 0, 0, 0)
        self.QrCodeData = QtWidgets.QTextEdit(Fcode)
        self.QrCodeData.setAlignment(Qt.AlignLeft | Qt.AlignTop)
        self.QrCodeData.setStyleSheet("QTextEdit {color: '#FFFFFF'; font-size: 16px; text-align: center; border: 4px solid white;"
                                     " border-radius: 10px; padding: 5px;"
                                     "background-color: transparent;}")
        self.QrCodeData.setGeometry(QtCore.QRect(600, 90, 300, 150))
        self.QrCodeData.setObjectName("QrCodeData")

        self.retranslateUi(Fcode)
        QtCore.QMetaObject.connectSlotsByName(Fcode)

    def retranslateUi(self, Fcode):
        _translate = QtCore.QCoreApplication.translate
        Fcode.setWindowTitle(_translate("Fcode", "Frame"))
        self.CancelBTN.setText(_translate("Fcode", "Export"))
        self.current.setText(_translate("Fcode", "Current"))
        self.history.setText(_translate("Fcode", "History"))
        self.FeedLabel.setStyleSheet("QLabel {border:8px solid white;"
                                     " border-radius: 20px; "
                                     "background-color: transparent;}")
        self.FeedLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.FeedLabel.setMaximumSize(QtCore.QSize(300, 300))
        self.movie = QMovie("./res/qr-code-scanner.gif")
        self.FeedLabel.setMovie(self.movie)
        self.movie.start()
        self.QrCodeData.setText(_translate("Fcode", "Scanning..."))
import background_rc
import qrcode_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fcode = QtWidgets.QFrame()
    ui = Ui_Fcode()
    ui.setupUi(Fcode)
    Fcode.show()
    sys.exit(app.exec_())
